"""empty message

Revision ID: 07b3042eb52d
Revises: 205e1b8bc4ac
Create Date: 2021-11-09 20:55:53.241293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b3042eb52d'
down_revision = '205e1b8bc4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Expert', 'trigramme')
    op.drop_column('Expert', 'numero')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expert', sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Expert', sa.Column('trigramme', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
