"""empty message

Revision ID: 205e1b8bc4ac
Revises: 175052c4b7db
Create Date: 2021-11-05 18:41:41.362523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205e1b8bc4ac'
down_revision = '175052c4b7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expert', sa.Column('numero', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Expert', 'numero')
    # ### end Alembic commands ###
