"""empty message

Revision ID: 3b63943976bb
Revises: 4969c13cc694
Create Date: 2021-12-05 10:47:45.257847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b63943976bb'
down_revision = '4969c13cc694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Agenda', 'Expert', ['Organisateur'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Agenda', 'Client', ['client_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Agenda_expert', 'Expert', ['Participant_invité'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Client_negotiateur', 'Client', ['client_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Facturation', 'Client', ['Destinataire'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Proprietaire'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Expert', ['expediteur'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Locataire'], ['id'])
    op.create_foreign_key(None, 'Facturation_history', 'Mission', ['mission'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('Mission', sa.Column('appli', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'compte_mensuel', 'Mission', ['mission'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'expert_facturation', 'Expert', ['expert_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'facturation_client', 'Client', ['client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'facturation_mission', 'Mission', ['ref_mission'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'suivi_client', 'Expert', ['responsable'], ['id'])
    op.create_foreign_key(None, 'suivi_client', 'Client', ['client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'suivi_prospect', 'Expert', ['responsable'], ['id'])
    op.create_foreign_key(None, 'suivi_prospect', 'prospect', ['prospect_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suivi_prospect', type_='foreignkey')
    op.drop_constraint(None, 'suivi_prospect', type_='foreignkey')
    op.drop_constraint(None, 'suivi_client', type_='foreignkey')
    op.drop_constraint(None, 'suivi_client', type_='foreignkey')
    op.drop_constraint(None, 'facturation_mission', type_='foreignkey')
    op.drop_constraint(None, 'facturation_client', type_='foreignkey')
    op.drop_constraint(None, 'expert_facturation', type_='foreignkey')
    op.drop_constraint(None, 'compte_mensuel', type_='foreignkey')
    op.drop_column('Mission', 'appli')
    op.drop_constraint(None, 'Facturation_history', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Client_negotiateur', type_='foreignkey')
    op.drop_constraint(None, 'Agenda_expert', type_='foreignkey')
    op.drop_constraint(None, 'Agenda', type_='foreignkey')
    op.drop_constraint(None, 'Agenda', type_='foreignkey')
    # ### end Alembic commands ###
