"""empty message

Revision ID: 59a71f5d95ff
Revises: 3b63943976bb
Create Date: 2021-12-07 11:07:49.039572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a71f5d95ff'
down_revision = '3b63943976bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Client', sa.Column('anom', sa.Boolean(), nullable=True))
    op.add_column('Client', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('anom', sa.Boolean(), nullable=True))
    op.add_column('Expert', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('prospect', sa.Column('anom', sa.Boolean(), nullable=True))
    op.add_column('prospect', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'reason')
    op.drop_column('prospect', 'anom')
    op.drop_column('Expert', 'reason')
    op.drop_column('Expert', 'anom')
    op.drop_column('Client', 'reason')
    op.drop_column('Client', 'anom')
    # ### end Alembic commands ###
