"""empty message

Revision ID: 78d273da62ed
Revises: 59a71f5d95ff
Create Date: 2021-12-13 10:00:51.911802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d273da62ed'
down_revision = '59a71f5d95ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compte_mensuel', sa.Column('releve', sa.DECIMAL(precision=65, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compte_mensuel', 'releve')
    # ### end Alembic commands ###
