"""empty message

Revision ID: 9ffb989565f2
Revises: 3406ea955341
Create Date: 2021-11-03 08:12:40.554905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffb989565f2'
down_revision = '3406ea955341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Mission', sa.Column('Facex', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Mission', 'Facex')
    # ### end Alembic commands ###
