"""empty message

Revision ID: a9a9de29510d
Revises: d5f282e87362
Create Date: 2021-11-16 13:38:34.024411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a9de29510d'
down_revision = 'd5f282e87362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Client', sa.Column('login', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Client', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Client', type_='unique')
    op.drop_column('Client', 'login')
    # ### end Alembic commands ###
