"""empty message

Revision ID: d5f282e87362
Revises: 07b3042eb52d
Create Date: 2021-11-09 20:56:36.424635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f282e87362'
down_revision = '07b3042eb52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expert', sa.Column('numero', sa.BigInteger(), nullable=True))
    op.add_column('Expert', sa.Column('trigramme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Expert', 'trigramme')
    op.drop_column('Expert', 'numero')
    # ### end Alembic commands ###
