"""empty message

Revision ID: ddd8b31e073b
Revises: 9ffb989565f2
Create Date: 2021-11-05 18:37:58.037445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd8b31e073b'
down_revision = '9ffb989565f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expert', sa.Column('taux_tvk', sa.DECIMAL(precision=65, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Expert', 'taux_tvk')
    # ### end Alembic commands ###
